### ISSUE TITLE
5.3.1 Warning: Cannot parse: Range Error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by stonebk** [reactjs/react-docgen#498] opened 2021-03-29 15:46 UTC
I recently updated `react-styleguidist` which brought `react-docgen` to `5.3.1` and I started getting a lot of warnings:

```
Warning: Cannot parse src/components/Input/Input.jsx: RangeError: Maximum call stack size exceeded

It usually means that react-docgen does not understand your source code, try to file an issue here:
https://github.com/reactjs/react-docgen/issues
```

If I switch back to `react-docgen@5.3.0`, all the warnings go away. I think it has something to do with using `@component` per the [recommendation of react-styleguidist when using styled-components](https://react-styleguidist.js.org/docs/thirdparties/#styled-components).

**Comment by stonebk** [comment] 2021-03-30 20:40
```jsx
import PropTypes from 'prop-types';
import styled from 'styled-components';
import { InputMixin } from '../../mixins/components/InputMixin';
import { INPUT_SIZES } from '../../constants/INPUT';
import FormControl from '../../js/FormControl';

/**                                                                                                                                                                                                                                           
 * An HTML text input component.                                                                                                                                                                                                              
 */
const Input = styled(FormControl)`                                                                                                                                                                                                            
    ${InputMixin}                                                                                                                                                                                                                             
`;

Input.displayName = 'Input';

Input.propTypes = {
    /**                                                                                                                                                                                                                                       
     * The size of the input.                                                                                                                                                                                                                 
     */
    size: PropTypes.oneOf(Object.keys(INPUT_SIZES)),
    /**                                                                                                                                                                                                                                       
     * The HTML input type.                                                                                                                                                                                                                   
     * @ignore                                                                                                                                                                                                                                
     */
    type: PropTypes.string,
    /**                                                                                                                                                                                                                                       
     * The input should fill the entire width of the container.                                                                                                                                                                               
     */
    fluid: PropTypes.bool,
};

Input.defaultProps = {
    size: INPUT_SIZES.md,
    type: 'text',
    fluid: true,
};

/** @component */
export default Input;

```

**Comment by phamquocduy** [comment] 2021-04-10 16:33
Same issue for me

**Comment by linxu** [comment] 2021-04-26 02:31
I have the same issue, someone solves it?

**Comment by Miklet** [comment] 2021-05-26 13:25
I had the same issue today and we were using `ast-types@0.12.4`. Verify if you don't use the incompatible version of this package.

**Comment by danez** [comment] 2023-04-15 09:49
duplicate of #590

**Closed by danez** 2023-04-15 09:49 UTC
