### ISSUE TITLE
With forwardRef Union types get lost

### ISSUE THREAD

**Issue by bmsuseluda** [reactjs/react-docgen#883] opened 2023-12-19 08:55 UTC
Hello together,

with the following usage of forwardRef union types get lost:
```ts
interface Props {
  /** The name to greet */
  name: "world" | "hello";
  title: string;
}

/**
 * Hello world component
 */
const MyComponent = forwardRef<ElementRef<"div">, Props>(
  ({name = 'world'}, ref) => {
    return <div />;
  }
);
```

A workaround is to add the type "Props to the spread as well:
```ts
interface Props {
  /** The name to greet */
  name: "world" | "hello";
  title: string;
}

/**
 * Hello world component
 */
const MyComponent = forwardRef<ElementRef<"div">, Props>(
  ({name = 'world'}: Props, ref) => {
    return <div />;
  }
);
```

But this is redundant because the type is already defined as a generic at the forwardRef function.

Would it be possible to support the generics of forwardRef?

Thanks in regards

**Comment by danez** [comment] 2023-12-20 13:45
Duplicate of #878

**Closed** 2023-12-20 13:45 UTC
Labels: new feature
