### ISSUE TITLE
getting error in a file written in ES6

### ISSUE THREAD

**Issue by ritz078** [reactjs/react-docgen#116] opened 2016-08-15 19:54 UTC
The file is [https://github.com/ritz078/react-filters/blob/canary/components/Slider/Slider.js](https://github.com/ritz078/react-filters/blob/canary/components/Slider/Slider.js)

The error I get is 

```
Error with path "./components/Slider/Slider.js": Error: [{type: ImportDefaultSpecifier, start: 370, end: 374, loc: [object Object], local: [object Object], id: null, name: null}] does not match type Printable
Error: [{type: ImportDefaultSpecifier, start: 370, end: 374, loc: [object Object], local: [object Object], id: null, name: null}] does not match type Printable
    at Type.Tp.assert (/Users/ritz078/.npm-packages/lib/node_modules/react-docgen/node_modules/recast/node_modules/ast-types/lib/types.js:56:15)
    at genericPrintNoParens (/Users/ritz078/.npm-packages/lib/node_modules/react-docgen/node_modules/recast/lib/printer.js:219:26)
    at genericPrint (/Users/ritz078/.npm-packages/lib/node_modules/react-docgen/node_modules/recast/lib/printer.js:164:9)
    at printRootGenerically (/Users/ritz078/.npm-packages/lib/node_modules/react-docgen/node_modules/recast/lib/printer.js:105:15)
    at maybeReprint (/Users/ritz078/.npm-packages/lib/node_modules/react-docgen/node_modules/recast/lib/printer.js:97:16)
    at print (/Users/ritz078/.npm-packages/lib/node_modules/react-docgen/node_modules/recast/lib/printer.js:75:29)
    at exports.printComments (/Users/ritz078/.npm-packages/lib/node_modules/react-docgen/node_modules/recast/lib/comments.js:324:22)
    at printWithComments (/Users/ritz078/.npm-packages/lib/node_modules/react-docgen/node_modules/recast/lib/printer.js:61:16)
    at print (/Users/ritz078/.npm-packages/lib/node_modules/react-docgen/node_modules/recast/lib/printer.js:66:20)
    at Printer.print (/Users/ritz078/.npm-packages/lib/node_modules/react-docgen/node_modules/recast/lib/printer.js:118:21)

```

The command I ran was ` react-docgen ./components/Slider/Slider.js`

**Comment by fkling** [comment] 2016-08-15 22:34
This is strange. I could image that react-docgen tries to include the raw source of `import noop ...` line, but looking through the ast-types definitions, `ImportDefaultSpecifier` inherits from `Printable`.

We will have to investigate where the issue is in ast-types / recast or work around it.

**Comment by levithomason** [comment] 2016-08-22 19:23
I'm also getting `does not match type Printable` errors.  Seems the cause is using a function as a defaultProp value:

```jsx
// import { Modal } from 'src/modules'

Confirm.defaultProps = {
  as: Modal,
  cancelButton: 'Cancel',
  confirmButton: 'OK',
  content: 'Are you sure?',
}
```

Where `as` is a `Modal` stateless functional component.  Prior to adding this defaultProp, we had no react-docgen errors.

**Comment by levithomason** [comment] 2016-08-22 20:50
OK, it is actually due to using an imported value in default props.  This PR fixes it https://github.com/reactjs/react-docgen/pull/99.

**Comment by levithomason** [comment] 2016-08-22 20:56
@ritz078 this issue should be resolved now that #99 is merged, albeit waiting for a release.

**Comment by ritz078** [comment] 2016-08-23 12:22
same. waiting for the release.

**Comment by fkling** [comment] 2016-08-25 16:19
Just release v2.10.0!

**Comment by levithomason** [comment] 2016-08-25 16:20
Nice!  Testing :D

**Comment by levithomason** [comment] 2016-08-25 16:24
Confirming imported defaults now work, very much appreciated @fkling.

```jsx
import { Checkbox } from '../../modules'

Radio.defaultProps = {
  as: Checkbox,
}
```

**Closed** 2016-08-25 16:26 UTC
Labels: bug
