### ISSUE TITLE
load variables from other files

### ISSUE THREAD

**Issue by chrisdrackett** [reactjs/react-docgen#170] opened 2017-03-31 16:16 UTC
We have a lot of our common variables (sizes, colors, etc) all defined in a single file. I like to reference these when building out propTypes. Currently docgen (via styleguidist) does not pick up these variables as they are all from an external file. It would be nice if there was a way to teach docgen to look at this variable file or similar. I'm going to see what I can figure out, but figured it was worth posting this in case anyone has had a similar issue and has already found a solution.

**Comment by dotcs** [comment] 2017-04-05 08:54
May be related to this issue: https://github.com/reactjs/react-docgen/issues/33

**Comment by n1313** [comment] 2017-06-12 07:49
I'm having the same problem: I have a bunch of string constants shared across many files and docgen (understandably) does not pick up their values when I use them in propType declarations. I think this use case is simpler than #33 and could probably be fixed by supplying docgen with a map of constants and doing a search-replace for them in AST data before emitting it.

**Comment by Palid** [comment] 2017-12-22 12:09
+1, this breaks rendering in react-styleguidist too :(

**Comment by danez** [comment] 2018-07-13 16:13
duplicate of #33

**Closed by danez** 2018-07-13 16:13 UTC
