### ISSUE TITLE
Add support for defining PropTypes using ES6 static getter

### ISSUE THREAD

**Issue by bsmith-cycorp** [reactjs/react-docgen#183] opened 2017-05-10 15:19 UTC
With the new push for ES6 class syntax over the now-deprecated React.createClass(), this issue has become a little bit more relevant. ES6 classes don't (yet) support static data members without a `MyClass.myProp = ...` outside of the main class definition. They do, however, support static getters, but that would mean returning something like `propTypes` from a function.

For example:

```
class MyComponent extends React.Component {

  static get propTypes() {
    return {
      ...
    }
  }

}
```
vs.
```
class MyComponent extends React.Component {

}

MyComponent.propTypes = {
  ...
}
```

It's not essential, but it would be really nice to be able to declare propTypes inside the ES6 class body and still have them be detected by react-docgen.

Issue created by recommendation of @fkling in the discussion on #151

**Comment by ycmjason** [comment] 2017-05-30 20:44
Totally agree.

**Comment by jesseko** [comment] 2017-08-10 18:32
Hi all, I wrote an attempt at this.
It works for me, but then we tried on a colleague's machine and we're getting "Maximum call stack size exceeded" errors that seem to just be deep in the guts of react-docgen.  Can you take a look and let me know if you have any thoughts on how to debug or fix this?  I wrote this and two other custom handlers and am having this problem with all of them -- would really appreciate some help.
You're welcome to adapt this code back into react-docgen (once it's more stable)

First the error: 
RangeError: Maximum call stack size exceeded
    at Type.value (/Volumes/code/main/node_modules/ast-types/lib/types.js:41:40)
    at Field.Fp.getValue (/Volumes/code/main/node_modules/ast-types/lib/types.js:255:26)
    at Object.getFieldValue (/Volumes/code/main/node_modules/ast-types/lib/types.js:680:30)
    at NodePath.NPp.getValueProperty (/Volumes/code/main/node_modules/ast-types/lib/node-path.js:124:22)
    at getChildPath (/Volumes/code/main/node_modules/ast-types/lib/path.js:52:37)
    at NodePath.get (/Volumes/code/main/node_modules/ast-types/lib/path.js:76:20)
    at visitChildren (/Volumes/code/main/node_modules/ast-types/lib/path-visitor.js:242:38)
    at Visitor.PVp.visitWithoutReset (/Volumes/code/main/node_modules/ast-types/lib/path-visitor.js:204:20)
    at NodePath.each (/Volumes/code/main/node_modules/ast-types/lib/path.js:101:26)
    at visitChildren (/Volumes/code/main/node_modules/ast-types/lib/path-visitor.js:219:18)

file attached (it's JS of course, but had to use ".txt" for github to let me attach)

[react-docgen-staticPropsHandler.txt](https://github.com/reactjs/react-docgen/files/1215945/react-docgen-staticPropsHandler.txt)

**Comment by jesseko** [comment] 2017-08-10 20:26
FYI, here's how I'm running the code above.  Should be very easy to duplicate this in any existing app.  I'm definitely curious whether the error will repro or whether it will just work for you:

```
let staticProptypesHandler = require('./react-docgen-staticPropsHandler').default;
...
let reactInfo;
try {
	const docHandlers = reactDocs.defaultHandlers.concat( [staticProptypesHandler] );
	const resolver = reactDocs.resolver.findExportedComponentDefinition;
	reactInfo = reactDocs.parse(contents, resolver, docHandlers);
} catch (e){
	console.log(e); //this is where I'm seeing the error I posted above
}
```

**Comment by jesseko** [comment] 2017-08-14 21:46
We've tested on a few more computers here -- working on some, not on others.  Not sure why the "Maximum call stack size exceeded" errors are inconsistent between machines, but in any case, we're hoping you all might be able to spot something bad I'm doing in the code, or just write a better handler for ES6 static proptypes.  Thanks.

**Comment by kabbi** [comment] 2017-08-15 09:41
In my experience, `Maximum call stack size exceeded` error happens sometimes when there are multiple `ast-types` dependencies present, and `react-docgen` uses the wrong one, which causes infinite loops. Verify that dependency trees are the same on different machines (you can use `npm ls`). It would be helpful for me if you provide any feedback on this.

**Comment by jesseko** [comment] 2017-08-17 18:31
Thanks @kabbi 
We took a look across our machines and the ast-types are consistent, but the trees under react-docgen are different. 
Here's mine, which are working, no errors:
├─┬ react-docgen@2.17.0
│ ├── async@2.5.0
│ ├── babylon@5.8.38
│ ├── commander@2.11.0
│ ├─┬ doctrine@2.0.0
│ │ └── isarray@1.0.0
│ ├── node-dir@0.1.17
│ └─┬ recast@0.12.6
│   ├── ast-types@0.9.11
│   └── esprima@4.0.0

Here's my colleage Eric's tree (he's getting the `Maximum call stack size exceeded` error):
├─┬ react-docgen@2.17.0
│ ├─┬ async@2.5.0
│ │ └── lodash@4.17.4
│ ├─┬ babel-runtime@6.25.0
│ │ ├── core-js@2.5.0
│ │ └── regenerator-runtime@0.10.5
│ ├── babylon@5.8.38
│ ├── commander@2.11.0
│ ├─┬ doctrine@2.0.0
│ │ ├── esutils@2.0.2
│ │ └── isarray@1.0.0
│ ├─┬ node-dir@0.1.17
│ │ └─┬ minimatch@3.0.4
│ │   └─┬ brace-expansion@1.1.8
│ │     ├── balanced-match@1.0.0
│ │     └── concat-map@0.0.1
│ └─┬ recast@0.12.6
│   ├── ast-types@0.9.11
│   ├── esprima@4.0.0
│   ├── private@0.1.7
│   └── source-map@0.5.6

Any more ideas?

**Comment by jesseko** [comment] 2017-09-21 00:01
I can work on this more if you all can help me get unstuck.

I don't see any loops in the error call stack (posted above)
Don't know how to gain any more insight into what's failing on some machines.

I could dig into react docgen code and add some logging to try to show something about what's running differently between machines.  Does that seem like a good idea?  Any ideas where/what to look for?  Or could do that in the ast-types code if that seems more likely?

...or if one of you is going to write a better fix for this ticket soon then I can just wait for that.

Please advise

**Comment by lensbart** [comment] 2017-10-05 17:31
For what's it worth, I'm getting the same `RangeError: Maximum call stack size exceeded` for all my components that are written as (pure) functions. I'm using react-docgen as part of react-styleguidist, and everything was working fine when all components were defined as classes, before applying the `react/prefer-stateless-function` rule of ESLint. Will update here if and when I found the cause.

**Comment by lensbart** [comment] 2017-10-05 20:49
Found it. Apparently this doesn't work:
```
import React from 'react'
export default function Blockquote(props) {
  return (
    <blockquote>
      {props.children}
    </blockquote>
  )
}
```
But this does:
```
import React from 'react'
module.exports = function Blockquote(props) {
  return (
    <blockquote>
      {props.children}
    </blockquote>
  )
}
```
Hope this helps!

**Comment by danez** [comment] 2017-10-05 21:10
@lensbart Thanks for the investigation. Which version of react-docgen are you using? 2.x or 3.0-beta?

**Comment by lensbart** [comment] 2017-10-05 21:14
I'm using react-docgen as part of react-styleguidist (v6.0.27), its `package.json` says that version 3.0.0-beta7 is used.

**Comment by fkling** [comment] 2017-10-11 00:39
@lensbart , @danez , I think it would be worth opening a new issue for that.

@jesseko, Thank you for working on this! I have since then worked on fixing this as well. Maybe you can try it when the new version is released and see if you also get call stack errors. If this is the same issue as @lensbart's, please consider opening a new issue and provide information to reproduce the issue, such as component definitions for which it fails.

**Closed** 2017-10-11 00:39 UTC
Labels: bug

**Comment by fkling** [comment] 2017-10-11 00:41
@lensbart , @danez: Potentially the same issue as #203 ?

**Comment by lensbart** [comment] 2017-10-11 22:44
My issue was solved after switching from npm to yarn.

**Comment by pke** [comment] 2017-11-24 23:18
@lensbart this doesn't seem to be a right solution for a parser problem? How can the package manager fix such issue?

**Comment by lensbart** [comment] 2017-11-24 23:28
It does seem strange, but I thought it could be due to some dependency incompatibility which got resolved by yarn (I didn't look much further into it)
