### ISSUE TITLE
Docblock for arrow class methods is not parsed

### ISSUE THREAD

**Issue by dmitrif** [reactjs/react-docgen#190] opened 2017-06-22 13:46 UTC
Hello!

Tested with both `v2` and `v3-beta`.

Given sample code of:

```javascript
import React from 'react';
import PropTypes from 'prop-types';

/**
 *  A generic component
 */
export default class GenericComponent extends React.PureComponent {
  static propTypes = {
    /** Children to render out in the ScrollLayout */
    children: PropTypes.node,
    /** Another prop */
    anotherProp: PropTypes.number,
  };

  static defaultProps = {
    children: undefined,
    anotherProp: 4,
  };

  /** Do something */
  doSomething = () => {
  };

  render() {

  }
}
```

React-docgen produces the following tree:
```json
{
  "description": "A generic component",
  "methods": [],
  "props": {
    "children": {
      "type": {
        "name": "node"
      },
      "required": false,
      "description": "Children to render out in the ScrollLayout",
      "defaultValue": {
        "value": "undefined",
        "computed": true
      }
    },
    "anotherProp": {
      "type": {
        "name": "number"
      },
      "required": false,
      "description": "Another prop",
      "defaultValue": {
        "value": "4",
        "computed": false
      }
    }
  }
}
```

If the method `doSomething` is instead written as: 
```javascript
doSomething() {}
```

Then the output is as expected:
```json
{
  "description": "A generic component",
  "methods": [
    {
      "name": "doSomething",
      "docblock": "Do something",
      "modifiers": [],
      "params": [],
      "returns": null,
      "description": "Do something"
    }
  ],
  "props": {
    "children": {
      "type": {
        "name": "node"
      },
      "required": false,
      "description": "Children to render out in the ScrollLayout",
      "defaultValue": {
        "value": "undefined",
        "computed": true
      }
    },
    "anotherProp": {
      "type": {
        "name": "number"
      },
      "required": false,
      "description": "Another prop",
      "defaultValue": {
        "value": "4",
        "computed": false
      }
    }
  }
}
```

Of course one can define their class methods as such, but then they will have to explicitly bind the function to contain the proper scope in the constructor.

Thank you!

**Comment by fkling** [comment] 2017-07-21 20:59
Duplicate of #182 actually.

**Closed by fkling** 2017-07-21 20:59 UTC
